# This Playbook pings the servers 
---
- name: "Ping Box's"
  hosts:
    - controller
    - managed1
    - managed2
  gather_facts: yes
  tasks:
  - action: ping
    register: hello
  - debug:
      var: hello
