# This Playbook reboots the servers if required
---
- name: Part 1 - Reboot Machine 1
  hosts:
    - managed1
  gather_facts: yes
  tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Perform reboot"
      reboot:
      become: yes
      when: reboot_required_file.stat.exists == true

- name: Part 2 - Reboot Machine 2
  hosts:
    - managed2
  gather_facts: yes
  tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Perform reboot"
      reboot:
      become: yes
      when: reboot_required_file.stat.exists == true
